### PR TITLE
Revise naming behaviour of products and targets

### PR DESCRIPTION
**Pull request by lyptt**
@yonaskolb Could you see if this branch exhibits the behaviour you expect regarding target/product naming?

### CODE REVIEW

**Comment by yonaskolb** [comment]
Hi @lyptt 
Thanks for looking at this. The generated targets now have the proper names.

There still seems to be an issue with linking to the frameworks though. 

If it helps, for the iOS target, the framework is grey instead of yellow in Xcode. It says it's referencing `build/debug`. If I remove the framework and add through Xcode, it works correctly and says the path is `build/debug-iphoneos`.

For testing you can use the latest comments in #144

**Comment by yonaskolb** [comment]
The actual build error is 
```
ld: framework not found OtherFramework_iOS
```

**Comment by lyptt** [comment]
@yonaskolb thanks for the info, can I use the project sample on the other ticket to reproduce this?

**Comment by yonaskolb** [comment]
Yes, the specs in #144 show this behaviour

**Comment by yonaskolb** [comment]
Hi @lyptt, any updates on this? I understand you may be too busy to work on struct at the moment

**Comment by yonaskolb** [comment]
Hi @lyptt. Is this still being worked on? Otherwise I might roll my own solution written in Swift

**Comment by yonaskolb** [comment]
Hi @lyptt, in case you're interested this is the solution I've been working on in Swift https://github.com/yonaskolb/XcodeGen
It doesn't quite handle everything `struct` does yet, but it already fulfils my use cases. I plan to build on it even more though. 
You've inspired me with your awesome tool, so just want to say thank you for all your hard work!

**Comment by jcampbell05** [comment]
@yonaskolb should be good to standardize this in swift :)  if you need any help, I'll be happy to help I also built a similar tool to this and struct.

https://github.com/jcampbell05/xcake

**Pull request closed without merging**
