### PR TITLE
Enabled support for deterministic project generation

### LINKED ISSUE #125: Deterministic generation
It would be great if the generated Xcode project was deterministically generated, meaning if it was generated with the same spec, the output would be the same.
This would aid in diffs (even though I know the aim of Struct is not to have the xcode project checked in), but more importantly would stop Xcode from reloading a project even though there are no real changes.

I'm not sure if you have any control over this, if you're using cocoapods' `xcodeproject`? 
There was a pull request there though that seemed to add this functionality https://github.com/CocoaPods/Xcodeproj/pull/283

### PR DESCRIPTION
**Pull request by lyptt**
Fixes #125

### CODE REVIEW

**Comment by yonaskolb** [comment]
Getting this released whenever you have time would make debugging issues easier, as the different struct option effects can be viewed in a project diff

**Comment by lyptt** [comment]
Hi @yonaskolb, you can make use of this right away without waiting for us to release if you checkout the code and install it from that:

```bash
git clone git@github.com:workshop/struct.git
cd struct
git checkout feature-deterministic-uuids
gem install bundler # no need to run this if you already can run 'bundle' in Terminal, may need sudo
gem install rake # no need to run this if you can already run 'rake' in Terminal, may need sudo
bundle install # may need sudo
rake install # may need sudo
```

**Comment by yonaskolb** [comment]
Thanks, that will help!

I actually tried to do this in a post generate script but it doesn't seem to work. Would you expect this to work?
```
run do |spec, xcodeproj|
    xcodeproj.predictabilize_uuids
end
```

**Comment by lyptt** [comment]
I would yes, there may be nuances in the ordering between the hooks and xcodeproj processing that cause it to randomise again though. I'm not sure if once you do predictabilize_uuids you're unable to touch the project again without it re-randomising.

It also may be worth you adding some `puts` statements to see if your hook is actually running.

**Comment by yonaskolb** [comment]
Looks as though hook wasn't actually running due to an problem I'll open an issue about. Once it's running though `predictabilize_uuids` in post-generate doesn't help however. Oh well

**Comment by lyptt** [comment]
Yeah @yonaskolb I'd try using this branch then, I've confirmed the UUIDs are stable after adding the command in the right place

**Comment by yonaskolb** [comment]
I tested this branch. It does in fact create an identical .xcodeproj file if the contents of the spec are EXACTLY the same.
However if anything changes in the spec, all the id's are created from scratch and rearranged, meaning the use case of seeing diffs in the xcodeproj file doesn't work.

An ideal solution would be to generate the id's sequentially like the Swift Package Manager does (OBJ_1, OBJ_2), or based on a common random seed and using the hashes of object names. That sort of functionality may be locked behind `cocoapods/xcodeproj` though

**Comment by lyptt** [comment]
That's interesting, because the documentation indicates that when using this method the IDs are based on MD5 hashes of each object, which is exactly what you're proposing.

**Comment by lyptt** [comment]
From looking into the diffs, it seems this does partially work, however the ordering of the objects within the pbxproj file seems to affect its MD5 hash for some reason, which is why the IDs still change. It seems like the object order is non-deterministic too, so even if the IDs are stable, your diff still won't be clean.

It _does_ have an impact though, the diff looks much nicer than before where every ID is included, so I'll still merge this.

**Comment by yonaskolb** [comment]
This seems to print a bunch of garbage to the console when generating. Looks like the the output of the xcodeproj

**Comment by yonaskolb** [comment]
```
PBXFileReference -- /mainGroup/children/children:children:|,|,|,|,displayName:iOS,isa:PBXGroup,name:iOS,sourceTree:<group>,,children:|,|,displayName:tvOS,isa:PBXGroup,name:tvOS,sourceTree:<group>

...hundreds more lines...
```

**Comment by lyptt** [comment]
Interesting, we're not logging anything. If you scroll to the very top, is there a warning abut duplicate UUIDs?

**Comment by yonaskolb** [comment]
Nope no warning. It actually begins like this:
```
Processing project 'project'...
[Xcodeproj] Generated duplicate UUIDs:

PBXFileReference -- /mainGroup/children/children:children:...
... hundreds of lines...

Saved 'PATH_TO_PROJECT/project.xcodeproj'
```

**Comment by lyptt** [comment]
Yeah I thought so - the `Generated duplicate UUIDs:` bit is what I was referring to. For now it may be safer to remove this functionality until it can be investigted further.

**Pull request merged**
